[2024-06-26 22:53:20,279] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-26T22:53:17.769701+00:00 [queued]>
[2024-06-26 22:53:20,300] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-26T22:53:17.769701+00:00 [queued]>
[2024-06-26 22:53:20,303] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 22:53:20,303] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2024-06-26 22:53:20,303] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 22:53:20,332] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-26 22:53:17.769701+00:00
[2024-06-26 22:53:20,338] {standard_task_runner.py:52} INFO - Started process 2010 to run task
[2024-06-26 22:53:20,349] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'manual__2024-06-26T22:53:17.769701+00:00', '--job-id', '3151', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmp3ltppgtb', '--error-file', '/tmp/tmp857jl05_']
[2024-06-26 22:53:20,356] {standard_task_runner.py:77} INFO - Job 3151: Subtask process_text
[2024-06-26 22:53:20,432] {logging_mixin.py:109} INFO - Running <TaskInstance: text_processing_dag_1.process_text manual__2024-06-26T22:53:17.769701+00:00 [running]> on host cf249bbdc0d0
[2024-06-26 22:53:20,546] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=text_processing_dag_1
AIRFLOW_CTX_TASK_ID=process_text
AIRFLOW_CTX_EXECUTION_DATE=2024-06-26T22:53:17.769701+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-26T22:53:17.769701+00:00
[2024-06-26 22:53:23,790] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 31, in process_text
    df.columns = map(str.lower, df.columns)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 563, in _set_axis
    labels = ensure_index(labels)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5601, in ensure_index
    index_like = list(index_like)
TypeError: descriptor 'lower' requires a 'str' object but received a 'int'
[2024-06-26 22:53:23,837] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=text_processing_dag_1, task_id=process_text, execution_date=20240626T225317, start_date=20240626T225320, end_date=20240626T225323
[2024-06-26 22:53:23,891] {standard_task_runner.py:92} ERROR - Failed to execute job 3151 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 31, in process_text
    df.columns = map(str.lower, df.columns)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 563, in _set_axis
    labels = ensure_index(labels)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5601, in ensure_index
    index_like = list(index_like)
TypeError: descriptor 'lower' requires a 'str' object but received a 'int'
[2024-06-26 22:53:23,952] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-06-26 22:53:24,023] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
