[2024-06-26 14:59:23,360] {processor.py:163} INFO - Started process (PID=20374) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:23,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 14:59:23,362] {logging_mixin.py:109} INFO - [2024-06-26 14:59:23,361] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:23,370] {logging_mixin.py:109} INFO - [2024-06-26 14:59:23,370] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 14:59:23,388] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:23,397] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.040 seconds
[2024-06-26 14:59:53,872] {processor.py:163} INFO - Started process (PID=20405) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:53,874] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 14:59:53,876] {logging_mixin.py:109} INFO - [2024-06-26 14:59:53,875] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:53,886] {logging_mixin.py:109} INFO - [2024-06-26 14:59:53,885] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 14:59:53,905] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 14:59:53,913] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.046 seconds
[2024-06-26 15:00:24,501] {processor.py:163} INFO - Started process (PID=20436) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:24,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:00:24,504] {logging_mixin.py:109} INFO - [2024-06-26 15:00:24,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:24,515] {logging_mixin.py:109} INFO - [2024-06-26 15:00:24,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:00:24,538] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:24,548] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.049 seconds
[2024-06-26 15:00:55,166] {processor.py:163} INFO - Started process (PID=20467) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:55,167] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:00:55,168] {logging_mixin.py:109} INFO - [2024-06-26 15:00:55,168] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:55,177] {logging_mixin.py:109} INFO - [2024-06-26 15:00:55,176] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:00:55,196] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:00:55,205] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.045 seconds
[2024-06-26 15:01:25,366] {processor.py:163} INFO - Started process (PID=20498) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:25,368] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:01:25,368] {logging_mixin.py:109} INFO - [2024-06-26 15:01:25,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:25,375] {logging_mixin.py:109} INFO - [2024-06-26 15:01:25,375] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:01:25,394] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:25,403] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.041 seconds
[2024-06-26 15:01:55,972] {processor.py:163} INFO - Started process (PID=20529) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:55,974] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:01:55,974] {logging_mixin.py:109} INFO - [2024-06-26 15:01:55,974] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:55,985] {logging_mixin.py:109} INFO - [2024-06-26 15:01:55,984] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:01:56,004] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:01:56,014] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.048 seconds
[2024-06-26 15:02:26,551] {processor.py:163} INFO - Started process (PID=20560) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:26,552] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:02:26,553] {logging_mixin.py:109} INFO - [2024-06-26 15:02:26,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:26,561] {logging_mixin.py:109} INFO - [2024-06-26 15:02:26,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:02:26,581] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:26,590] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.042 seconds
[2024-06-26 15:02:57,041] {processor.py:163} INFO - Started process (PID=20591) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:57,042] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:02:57,043] {logging_mixin.py:109} INFO - [2024-06-26 15:02:57,042] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:57,052] {logging_mixin.py:109} INFO - [2024-06-26 15:02:57,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:02:57,071] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:02:57,080] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.043 seconds
[2024-06-26 15:03:27,809] {processor.py:163} INFO - Started process (PID=20622) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:27,811] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:03:27,811] {logging_mixin.py:109} INFO - [2024-06-26 15:03:27,811] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:27,819] {logging_mixin.py:109} INFO - [2024-06-26 15:03:27,818] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
  File "/opt/airflow/dags/../scripts/kafkaProducer.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-26 15:03:27,842] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:27,851] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.045 seconds
[2024-06-26 15:03:58,107] {processor.py:163} INFO - Started process (PID=20653) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:58,112] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:03:58,113] {logging_mixin.py:109} INFO - [2024-06-26 15:03:58,112] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:58,119] {logging_mixin.py:109} INFO - [2024-06-26 15:03:58,119] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
ModuleNotFoundError: No module named 'kafkaProducer'
[2024-06-26 15:03:58,141] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:03:58,169] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.065 seconds
[2024-06-26 15:04:28,791] {processor.py:163} INFO - Started process (PID=20684) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:28,794] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:04:28,794] {logging_mixin.py:109} INFO - [2024-06-26 15:04:28,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:28,801] {logging_mixin.py:109} INFO - [2024-06-26 15:04:28,800] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
ModuleNotFoundError: No module named 'kafkaProducer'
[2024-06-26 15:04:28,836] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:28,860] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.075 seconds
[2024-06-26 15:04:59,198] {processor.py:163} INFO - Started process (PID=20715) to work on /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:59,199] {processor.py:642} INFO - Processing file /opt/airflow/dags/kafka_producer.py for tasks to queue
[2024-06-26 15:04:59,199] {logging_mixin.py:109} INFO - [2024-06-26 15:04:59,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:59,205] {logging_mixin.py:109} INFO - [2024-06-26 15:04:59,205] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kafka_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_producer.py", line 12, in <module>
    from kafkaProducer import process_text  # Importing the process_text function
ModuleNotFoundError: No module named 'kafkaProducer'
[2024-06-26 15:04:59,227] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_producer.py
[2024-06-26 15:04:59,241] {processor.py:171} INFO - Processing /opt/airflow/dags/kafka_producer.py took 0.047 seconds
