[2024-06-25 04:54:55,359] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-25 04:54:55,419] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-25 04:54:55,419] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,419] {taskinstance.py:1244} INFO - Starting attempt 3 of 4
[2024-06-25 04:54:55,420] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,474] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-18 00:00:00+00:00
[2024-06-25 04:54:55,502] {standard_task_runner.py:52} INFO - Started process 3371 to run task
[2024-06-25 04:54:55,556] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'scheduled__2024-06-18T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmpqabmshrd', '--error-file', '/tmp/tmptf3y7mwi']
[2024-06-25 04:54:55,620] {standard_task_runner.py:77} INFO - Job 148: Subtask process_text
[2024-06-25 04:54:55,935] {standard_task_runner.py:92} ERROR - Failed to execute job 148 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 287, in task_run
    ti = _get_ti(task, args.execution_date_or_run_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 86, in _get_ti
    dag_run = _get_dag_run(task.dag, exec_date_or_run_id, create_if_necssary, session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 80, in _get_dag_run
    ) from None
airflow.exceptions.DagRunNotFound: DagRun for text_processing_dag_1 with run_id or execution_date of 'scheduled__2024-06-18T00:00:00+00:00' not found
[2024-06-25 04:54:56,003] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-07-12 00:26:50,616] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-07-12 00:26:50,682] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-07-12 00:26:50,682] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 00:26:50,682] {taskinstance.py:1244} INFO - Starting attempt 3 of 4
[2024-07-12 00:26:50,682] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 00:26:50,751] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-18 00:00:00+00:00
[2024-07-12 00:26:50,799] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'scheduled__2024-06-18T00:00:00+00:00', '--job-id', '3188', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmpinv8esi6', '--error-file', '/tmp/tmp_wsnpk0j']
[2024-07-12 00:26:50,803] {standard_task_runner.py:77} INFO - Job 3188: Subtask process_text
[2024-07-12 00:26:50,766] {standard_task_runner.py:52} INFO - Started process 4674 to run task
[2024-07-12 00:26:51,183] {logging_mixin.py:109} INFO - Running <TaskInstance: text_processing_dag_1.process_text scheduled__2024-06-18T00:00:00+00:00 [running]> on host cf249bbdc0d0
[2024-07-12 00:26:51,770] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=text_processing_dag_1
AIRFLOW_CTX_TASK_ID=process_text
AIRFLOW_CTX_EXECUTION_DATE=2024-06-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-18T00:00:00+00:00
[2024-07-12 00:26:59,352] {logging_mixin.py:109} INFO - Index(['date', 'time', 'messages', 'video_links', 'video_durations'], dtype='object')
[2024-07-12 00:28:24,725] {logging_mixin.py:109} INFO - Error: ZERO_RESULTS for city: شهيد
[2024-07-12 00:28:25,397] {logging_mixin.py:109} INFO - Error: ZERO_RESULTS for city: mosque
[2024-07-12 00:28:34,396] {logging_mixin.py:109} INFO - Error: ZERO_RESULTS for city: الأهالي
[2024-07-12 00:28:39,707] {local_task_job.py:212} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-07-12 00:28:39,741] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 4674. PIDs of all processes in the group: [4674]
[2024-07-12 00:28:39,853] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 4674
[2024-07-12 00:28:39,878] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-12 00:28:39,879] {logging_mixin.py:109} INFO - Error fetching data for city: north+gaza, Error: Task received SIGTERM signal
[2024-07-12 00:28:40,548] {logging_mixin.py:109} INFO - Error: ZERO_RESULTS for city: Maythaloun
[2024-07-12 00:28:41,145] {logging_mixin.py:109} INFO - Processed data saved to /opt/airflow/data/processed_data_1.json
[2024-07-12 00:28:41,164] {python.py:175} INFO - Done. Returned value was: None
[2024-07-12 00:28:41,220] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=text_processing_dag_1, task_id=process_text, execution_date=20240618T000000, start_date=20240712T002650, end_date=20240712T002841
[2024-07-12 00:28:41,310] {process_utils.py:70} INFO - Process psutil.Process(pid=4674, status='terminated', exitcode=0, started='00:26:50') (4674) terminated with exit code 0
