[2024-06-25 04:54:55,383] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-25T04:48:17.890992+00:00 [queued]>
[2024-06-25 04:54:55,435] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-25T04:48:17.890992+00:00 [queued]>
[2024-06-25 04:54:55,435] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,435] {taskinstance.py:1244} INFO - Starting attempt 3 of 4
[2024-06-25 04:54:55,435] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,518] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-25 04:48:17.890992+00:00
[2024-06-25 04:54:55,574] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'manual__2024-06-25T04:48:17.890992+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmp216w1adu', '--error-file', '/tmp/tmpcjhz5veg']
[2024-06-25 04:54:55,579] {standard_task_runner.py:77} INFO - Job 149: Subtask process_text
[2024-06-25 04:54:55,552] {standard_task_runner.py:52} INFO - Started process 3373 to run task
[2024-06-25 04:54:55,796] {standard_task_runner.py:92} ERROR - Failed to execute job 149 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 287, in task_run
    ti = _get_ti(task, args.execution_date_or_run_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 92, in _get_ti
    ti.refresh_from_task(task)
AttributeError: 'NoneType' object has no attribute 'refresh_from_task'
[2024-06-25 04:54:55,846] {local_task_job.py:154} INFO - Task exited with return code 1
